'pull_request_title': 'feat(localize): updated translation from Crowdin'
'pull_request_labels': ['crowdin']

files:
  - source: /src/locales/en/*.json
    translation: /src/locales/%locale%/%original_file_name%
