name: Dependency Review

on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout for dependency review
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938

      - name: Running Dependency Review
        uses: actions/dependency-review-action@0659a74c94536054bfa5aeb92241f70d680cc78e
